class ObjectPool:
    def __init__(self, generator, cleaner=lambda x: x, initial_size=1):
        self._objects = []
        self._checked_out_objects = {}
        self._generator = generator
        self._cleaner = cleaner
        for i in range(0, initial_size):
            self._objects.append(generator())
    
    def get(self):
        if len(self._objects) > 0:
            obj = self._objects.pop()
        else:
            obj = self._generator()
        self._checked_out_objects[id(obj)] = obj
        return obj
    
    def put_back(self, obj):
        self._cleaner(obj)
        self._objects.append(obj)
        if id(obj) in self._checked_out_objects:
            del self._checked_out_objects[id(obj)]
            
    def put_back_all(self):
        "Cleans and flags unused all objects ever generated by this pool. Very important to call this responsibly."
        for key in list(self._checked_out_objects.keys()):
            obj = self._checked_out_objects[key]
            self.put_back(obj)
        
SET_POOL = ObjectPool(lambda: set(), lambda x: x.clear(), 0)
DICT_POOL = ObjectPool(lambda: {}, lambda x: x.clear(), 0)
        
