import sets

class ObjectPool:
    def __init__(self, generator, cleaner=lambda x: x, initial_size=1):
        self._objects = []
        self._checked_out_objects = sets.Set()
        self._generator = generator
        self._cleaner = cleaner
        for i in range(0, initial_size):
            self._objects.append(generator())
    
    def get(self):
        if len(self._objects) > 0:
            obj = self._objects.pop()
        else:
            obj = self._generator()
        self._checked_out_objects.add(obj)
        return obj
    
    def put_back(self, obj):
        self._cleaner(obj)
        self._objects.append(obj)
        if obj in self._checked_out_objects:
            self._checked_out_objects.remove(obj)
            
    def put_back_all(self):
        "Cleans and flags unused all objects ever generated by this pool. Very important to call this responsibly."
        while len(self._checked_out_objects) > 0:
            obj = self._checked_out_objects.pop()
            self.put_back(obj)
        
SET_POOL = ObjectPool(lambda: sets.Set(), lambda x: x.clear(), 0)
DICT_POOL = ObjectPool(lambda: {}, lambda x: x.clear(), 0)
        